stuff and updated nginx

diff --git a/config/k8s/app/hydra/init-job.yml b/config/k8s/app/hydra/init-job.yml
--- a/config/k8s/app/hydra/init-job.yml
+++ b/config/k8s/app/hydra/init-job.yml
@@ -3,7 +3,7 @@ kind: Job
 metadata:
   name: hydra-init
 spec:
-  ttlSecondsAfterFinished: 300
+  ttlSecondsAfterFinished: 864000 # 60 * 60 * 24 * 10
   template:
     spec:
       containers:
@@ -14,18 +14,13 @@ spec:
         args:
         - |
           set -eu
-
           ts() {
             date '+%Y-%m-%dT%H:%M:%SZ' --utc
           }
-
           TIMEOUT=60
           END=$(($(date +%s) + TIMEOUT))
           while true; do
-            if [ "$(date +%s)" -gt ${END} ]; then
-              echo "[$(ts)] ERROR | timed out waiting for hydra to start"
-              exit 1
-            fi
+            if [ "$(date +%s)" -gt ${END} ]; then echo "[$(ts)] ERROR | timed out waiting for hydra to start"; exit 1; fi
             if ! nc -w 1 -z hydra 4445; then
               echo "[$(ts)] INFO | waiting..."
               sleep 1
@@ -34,14 +29,9 @@ spec:
               break
             fi
           done
-
           for file in $(ls /etc/hydra/config/*.json); do
             echo "[$(ts)] INFO | POST /clients < ${file}"
-            curl -X POST -sSi \
-              "http://hydra.default.svc.cluster.local:4445/clients" \
-              -H "Content-Type: application/json" \
-              -H "X-Forwarded-Proto: https" \
-              -d "@${file}"
+            curl -X POST -sSi "http://hydra.default.svc.cluster.local:4445/clients" -H "Content-Type: application/json" -H "X-Forwarded-Proto: https" -d "@${file}"
             echo
           done
         volumeMounts:
