stuff or whatever idk

diff --git a/scripts/infra/ansible b/scripts/infra/ansible
--- a/scripts/infra/ansible
+++ b/scripts/infra/ansible
@@ -1,15 +1,29 @@
-#!/bin/sh
+#!/usr/bin/bash
 
-set -eu
+set -euo pipefail
 
 name="$(basename $0)"
+root="$(pwd)"
+p="$(realpath "${BASH_SOURCE[0]}")"
+dir="$(dirname $p)"
+
+if [ "${dir: -13}" == "scripts/infra" ]; then
+  root="$(realpath --logical "${dir}/../../")"
+else
+  echo "Error: the asumption is that this script is in ./scripts/infra/"
+  exit 1
+fi
+
+rel="$(realpath --relative-to="${root}" "$(pwd)")"
+container_working_dir="/home/ansible/hrry.me/${rel}"
 
 docker compose \
-  --project-directory "$(pwd)" \
-  --file config/docker-compose.tools.yml \
+  --project-directory "${root}" \
+  --file "${root}/config/docker-compose.tools.yml" \
   --ansi never                           \
   run \
-    --interactive=true \
-    --no-deps           \
-    --rm                \
+    --interactive=true                   \
+    --workdir "${container_working_dir}" \
+    --no-deps                            \
+    --rm                                 \
     ansible "${name}" "$@"
diff --git a/scripts/tools/bake b/scripts/tools/bake
--- a/scripts/tools/bake
+++ b/scripts/tools/bake
@@ -38,7 +38,7 @@ usage() {
   echo
   echo "Flags"
   echo "  -h --help              print help message"
-  echo "     --local             load images locally"
+  echo "  -l --local             load images locally"
   echo "     --registry <uri>    change the registry (default \"$REG\")"
   echo "     --platform <s>      target a spesific platform"
   echo "     --prune             delete all the images and their tags (default: false)"
@@ -50,16 +50,22 @@ is_local=false
 prune=false
 verbose=false
 platform=""
+push=false
 while [ $# -gt 0 ]; do
   case $1 in
   	-h|--help)
       usage
       exit 0
       ;;
-    --local)
+    -l|--local)
       is_local=true
       GIT_BRANCH=""
       GIT_COMMIT=""
+      shift 1
+      ;;
+    --push)
+      push=true
+      args+=("--push")
       shift 1
       ;;
     --registry)
@@ -91,11 +97,16 @@ while [ $# -gt 0 ]; do
 done
 
 if ${is_local}; then
-  args+=("--set" "*.platform=$(get_platform)")
+  if ${push}; then
+    echo "Error: should not use --push and --local together"
+    exit 1
+  fi
+  args+=("--set" "*.platform=local")
   GIT_TAG=dev
   GIT_BRANCH=dev
   GIT_COMMIT=dev
   export GIT_GIT GIT_BRANCH GIT_COMMIT SOURCE_HASH
+  export _IS_LOCAL=true
 elif ${prune}; then
   docker image ls | grep "${REG}" #| awk '{print $3}'
   docker image rm -f $(docker image ls | grep "${REG}" | awk '{print $3}')
